/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    stores: Store;
    products: Product;
    variants: Variant;
    offers: Offer;
    redirects: Redirect;
    authors: Author;
    contents: Content;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'variants';
      offers: 'offers';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    contents: ContentsSelect<false> | ContentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Administrador: tudo. Editor: publica e cuida de ofertas. Redator: só rascunhos.
   */
  role: 'admin' | 'editor' | 'redator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Envie imagens JPG, PNG, WebP ou AVIF de até 4 MB. Reduza fotos maiores antes de enviar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para quem não pode vê-la (acessibilidade e SEO).
   */
  alt: string;
  /**
   * Ex.: "Divulgação LG". Use só imagens oficiais de imprensa ou com permissão.
   */
  credit: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categorias (1º nível) e subcategorias (2º nível). Especificações e critérios de nota ficam nas subcategorias.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Gerado a partir do nome se ficar vazio. Só letras minúsculas, números e hífens.
   */
  slug?: string | null;
  /**
   * Vazio = categoria de 1º nível. Preenchido = subcategoria.
   */
  parent?: (number | null) | Category;
  order?: number | null;
  active?: boolean | null;
  isAnchor?: boolean | null;
  description?: string | null;
  /**
   * Um emoji (ex.: 📺) ou nome de ícone.
   */
  icon?: string | null;
  /**
   * Campos que todo produto desta subcategoria terá. A chave não deve mudar depois de criada.
   */
  specTemplate?:
    | {
        /**
         * ex.: taxa_atualizacao
         */
        key: string;
        label: string;
        type: 'number' | 'text' | 'boolean' | 'option';
        unit?: string | null;
        /**
         * ex.: Imagem
         */
        group?: string | null;
        direction?: ('higher' | 'lower' | 'neutral') | null;
        options?: string[] | null;
        highlight?: boolean | null;
        comparable?: boolean | null;
        required?: boolean | null;
        perVariant?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * A soma dos pesos precisa ser exatamente 100.
   */
  criteria?:
    | {
        /**
         * ex.: custo_beneficio
         */
        key: string;
        name: string;
        weight: number;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Gerado a partir do nome se ficar vazio. Só letras minúsculas, números e hífens.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  description?: string | null;
  officialSite?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  name: string;
  /**
   * Gerado a partir do nome se ficar vazio. Só letras minúsculas, números e hífens.
   */
  slug?: string | null;
  logo?: (number | null) | Media;
  affiliateProgram?: string | null;
  /**
   * Loja inativa: os links /ir/ dela levam para a página do produto.
   */
  active?: boolean | null;
  /**
   * Regras do programa (ex.: "não exibir preço", "não usar imagens").
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * ex.: LG C4
   */
  name: string;
  /**
   * Gerado a partir do nome se ficar vazio. Só letras minúsculas, números e hífens.
   */
  slug?: string | null;
  status: 'rascunho' | 'ficha' | 'analise';
  /**
   * Calculada pelas notas de cada critério.
   */
  finalScore?: number | null;
  hasActiveOffer?: boolean | null;
  publishedAt?: string | null;
  reviewedAt?: string | null;
  brand: number | Brand;
  subcategory: number | Category;
  /**
   * A primeira é a principal.
   */
  images?: (number | Media)[] | null;
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  offers?: {
    docs?: (number | Offer)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * As linhas vêm do modelo da subcategoria. Salve para atualizar a lista.
   */
  specs?:
    | {
        key: string;
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * De 0 a 10, com uma casa decimal. As linhas vêm dos critérios da subcategoria.
   */
  scores?:
    | {
        key: string;
        label?: string | null;
        score?: number | null;
        justification?: string | null;
        id?: string | null;
      }[]
    | null;
  verdict?: string | null;
  pros?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  recommendedFor?: string | null;
  avoidIf?: string | null;
  fullReview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sources?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    /**
     * 70 a 160 caracteres. Se ficar vazia, o veredito é usado.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  product: number | Product;
  /**
   * ex.: 55", 220 V, 8 GB/256 GB
   */
  label: string;
  /**
   * ex.: OLED55C4PSA
   */
  modelCode?: string | null;
  voltage?: ('127v' | '220v' | 'bivolt') | null;
  /**
   * A usada em cards, listas e comparativos. Só uma por produto.
   */
  isReference?: boolean | null;
  /**
   * As linhas vêm do modelo da subcategoria (atributos que variam por variante).
   */
  specs?:
    | {
        key: string;
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Único lugar onde links e preços são editados. Os botões do site usam /ir/{id}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  product: number | Product;
  variant: number | Variant;
  store: number | Store;
  url: string;
  /**
   * Destino real do botão. Trocar aqui vale na hora em todo o site.
   */
  affiliateUrl: string;
  priceMin: number;
  priceMax: number;
  verifiedAt: string;
  status: 'active' | 'unavailable';
  notes?: string | null;
  title?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Endereços antigos que levam para os novos (301). Criados automaticamente quando um slug público muda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  type: '301';
  auto?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem assina os conteúdos. Na v1 há só a "Equipe DeciCompra"; não crie autores fictícios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Gerado a partir do nome se ficar vazio. Só letras minúsculas, números e hífens.
   */
  slug?: string | null;
  bio?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Melhores, Comparativos, Guias e Entenda. Análises de produto ficam no próprio Produto.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contents".
 */
export interface Content {
  id: number;
  title: string;
  /**
   * Gerado a partir do nome se ficar vazio. Só letras minúsculas, números e hífens.
   */
  slug?: string | null;
  type: 'melhores' | 'comparativo' | 'guia' | 'entenda';
  status: 'rascunho' | 'em_revisao' | 'publicado' | 'agendado';
  /**
   * Preenchida ao publicar. Para agendar, escolha uma data futura.
   */
  publishAt?: string | null;
  reviewedAt?: string | null;
  author?: (number | null) | Author;
  /**
   * Desativado na v1. Nunca permitido em Melhores ou Comparativo.
   */
  sponsored?: boolean | null;
  /**
   * Calculado ao salvar.
   */
  referencedProducts?: (number | Product)[] | null;
  productSetKey?: string | null;
  /**
   * No comparativo, é definida pelos produtos.
   */
  primarySubcategory?: (number | null) | Category;
  relatedSubcategories?: (number | Category)[] | null;
  /**
   * A resposta em poucas linhas, no topo da página.
   */
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  modelsAnalyzed?: number | null;
  /**
   * De 3 a 10 escolhas, por perfil (ex.: "Melhor custo-benefício").
   */
  picks?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        profileLabel: string;
        position?: number | null;
        why?: string | null;
        id?: string | null;
      }[]
    | null;
  alsoConsidered?:
    | {
        product?: (number | null) | Product;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 2 ou 3 produtos da mesma subcategoria. O endereço é gerado a partir deles.
   */
  comparedProducts?: (number | Product)[] | null;
  badges?:
    | {
        product?: (number | null) | Product;
        /**
         * ex.: Vencedora geral
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  chooseIf?:
    | {
        product?: (number | null) | Product;
        text: string;
        id?: string | null;
      }[]
    | null;
  specOverrides?:
    | {
        attributeKey: string;
        winner?: (number | null) | Product;
        noWinner?: boolean | null;
        justification: string;
        id?: string | null;
      }[]
    | null;
  conclusion?: string | null;
  sources?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    /**
     * 70 a 160 caracteres. Se ficar vazia, o resumo é usado.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'contents';
        value: number | Content;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  order?: T;
  active?: T;
  isAnchor?: T;
  description?: T;
  icon?: T;
  specTemplate?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        unit?: T;
        group?: T;
        direction?: T;
        options?: T;
        highlight?: T;
        comparable?: T;
        required?: T;
        perVariant?: T;
        id?: T;
      };
  criteria?:
    | T
    | {
        key?: T;
        name?: T;
        weight?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  officialSite?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  affiliateProgram?: T;
  active?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  finalScore?: T;
  hasActiveOffer?: T;
  publishedAt?: T;
  reviewedAt?: T;
  brand?: T;
  subcategory?: T;
  images?: T;
  variants?: T;
  offers?: T;
  specs?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  scores?:
    | T
    | {
        key?: T;
        label?: T;
        score?: T;
        justification?: T;
        id?: T;
      };
  verdict?: T;
  pros?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  recommendedFor?: T;
  avoidIf?: T;
  fullReview?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  product?: T;
  label?: T;
  modelCode?: T;
  voltage?: T;
  isReference?: T;
  specs?:
    | T
    | {
        key?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  product?: T;
  variant?: T;
  store?: T;
  url?: T;
  affiliateUrl?: T;
  priceMin?: T;
  priceMax?: T;
  verifiedAt?: T;
  status?: T;
  notes?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  auto?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  bio?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contents_select".
 */
export interface ContentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  status?: T;
  publishAt?: T;
  reviewedAt?: T;
  author?: T;
  sponsored?: T;
  referencedProducts?: T;
  productSetKey?: T;
  primarySubcategory?: T;
  relatedSubcategories?: T;
  summary?: T;
  body?: T;
  modelsAnalyzed?: T;
  picks?:
    | T
    | {
        product?: T;
        variant?: T;
        profileLabel?: T;
        position?: T;
        why?: T;
        id?: T;
      };
  alsoConsidered?:
    | T
    | {
        product?: T;
        reason?: T;
        id?: T;
      };
  comparedProducts?: T;
  badges?:
    | T
    | {
        product?: T;
        label?: T;
        id?: T;
      };
  chooseIf?:
    | T
    | {
        product?: T;
        text?: T;
        id?: T;
      };
  specOverrides?:
    | T
    | {
        attributeKey?: T;
        winner?: T;
        noWinner?: T;
        justification?: T;
        id?: T;
      };
  conclusion?: T;
  sources?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Vazio: usa o menu padrão (Categorias, Melhores, Comparativos, Guias, Entenda).
   */
  mainNav?:
    | {
        label: string;
        /**
         * ex.: /guias/
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vazio: usa o rodapé padrão.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * ex.: /guias/
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  affiliateNotice: string;
  /**
   * Ligue só depois da aprovação do AdSense.
   */
  adsEnabled?: boolean | null;
  /**
   * ex.: ca-pub-0000000000000000
   */
  adsenseClientId?: string | null;
  adSlots?:
    | {
        placement: 'home' | 'content' | 'sidebar';
        slotId: string;
        id?: string | null;
      }[]
    | null;
  adsTxt?: string | null;
  /**
   * ex.: G-XXXXXXXXXX. Só carrega para quem aceitar os cookies de estatísticas.
   */
  ga4Id?: string | null;
  contactEmail?: string | null;
  /**
   * Desligado: nenhuma página aparece no Google (robots.txt bloqueia tudo). Ligue só no lançamento, com o domínio definitivo configurado.
   */
  indexingEnabled?: boolean | null;
  /**
   * Só o valor de "content" da meta tag que o Search Console mostra no método "Tag HTML".
   */
  searchConsoleVerification?: string | null;
  /**
   * Aparece na Política de Privacidade (LGPD).
   */
  responsibleName?: string | null;
  /**
   * Aparece na Política de Privacidade para pedidos de titulares (LGPD).
   */
  privacyEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Foto de produtos à direita do título. No celular ela não aparece.
   */
  heroImage?: (number | null) | Media;
  searchChips?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  subcategoryCards?: (number | Category)[] | null;
  featuredComparisons?: (number | Content)[] | null;
  featuredBest?: (number | Content)[] | null;
  featuredGuides?: (number | Content)[] | null;
  featuredExplainers?: (number | Content)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  affiliateNotice?: T;
  adsEnabled?: T;
  adsenseClientId?: T;
  adSlots?:
    | T
    | {
        placement?: T;
        slotId?: T;
        id?: T;
      };
  adsTxt?: T;
  ga4Id?: T;
  contactEmail?: T;
  indexingEnabled?: T;
  searchConsoleVerification?: T;
  responsibleName?: T;
  privacyEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroImage?: T;
  searchChips?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  subcategoryCards?: T;
  featuredComparisons?: T;
  featuredBest?: T;
  featuredGuides?: T;
  featuredExplainers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}